views:
  - type: sections
    title: Home Assistant
    path: home
    icon: mdi:home-assistant
    sections:
      - type: grid
        cards:
          - type: tile
            entity: button.esp32c6_test_get_radar_parameters
            layout_options:
              grid_columns: 2
              grid_rows: 1
            name: Get Radar Parameters
            color: brown
          - type: tile
            entity: button.esp32c6_test_reset
            name: Reset
            color: red
          - type: tile
            entity: sensor.esp32c6_test_falling_information
            layout_options:
              grid_columns: 4
              grid_rows: 1
            name: Falling Information
            color: red
          - type: tile
            entity: binary_sensor.esp32c6_test_person_information
            layout_options:
              grid_columns: 4
              grid_rows: 1
            color: primary
            name: Person Information
          - features:
              - type: select-options
            type: tile
            entity: select.esp32c6_test_set_sensitivity
            layout_options:
              grid_columns: 4
              grid_rows: 1
            name: Set Sensitivity
          - features:
              - type: select-options
            type: tile
            entity: select.esp32c6_test_set_install_height
            layout_options:
              grid_columns: 4
              grid_rows: 1
            name: Set Install Height
          - features:
              - type: select-options
            type: tile
            entity: select.esp32c6_test_set_height_threshold
            layout_options:
              grid_columns: 4
              grid_rows: 1
            name: Set Height Threshold
        title: MR60BHA2
